In [1]:
import numpy as np
import pandas as pd

In [2]:
movies_df = pd.read_csv("movies.csv")
rating_df = pd.read_csv("ratings_sample.csv")

In [3]:
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
movies_df["year"] = movies_df.title.str.extract(r"(\(\d\d\d\d\))", expand=False)
movies_df["year"] = movies_df.year.str.extract(r"(\d\d\d\d)", expand=False)
movies_df["title"] = movies_df.title.str.replace(r"(\(\d\d\d\d\))", "", regex=True)
movies_df["title"] = movies_df.title.apply(lambda x: x.strip())
movies_df.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

In [5]:
movies_df = movies_df.drop("genres", axis=1)
movies_df.head()

   movieId                        title  year
0        1                    Toy Story  1995
1        2                      Jumanji  1995
2        3             Grumpier Old Men  1995
3        4            Waiting to Exhale  1995
4        5  Father of the Bride Part II  1995

In [6]:
rating_df.head()

   userId  movieId  rating   timestamp
0       1      169     2.5  1204927694
1       1     2471     3.0  1204927438
2       1    48516     5.0  1204927435
3       2     2571     3.5  1436165433
4       2   109487     4.0  1436165496

In [8]:
rating_df = rating_df.drop("timestamp", axis=1)
rating_df.head()

   userId  movieId  rating
0       1      169     2.5
1       1     2471     3.0
2       1    48516     5.0
3       2     2571     3.5
4       2   109487     4.0

In [9]:
userInput = [
    { "title":"Breakfast Club, The", "rating":5 },
    { "title":"Toy Story", "rating":3.5 },
    { "title":"Jumanji", "rating":2 },
    { "title":"Pulp Fiction", "rating":5 },
    { "title":"Akira", "rating":4.5}
]

inputMovies_df = pd.DataFrame(userInput)
inputMovies_df.head()

                 title  rating
0  Breakfast Club, The     5.0
1            Toy Story     3.5
2              Jumanji     2.0
3         Pulp Fiction     5.0
4                Akira     4.5

In [10]:
inputId = movies_df[movies_df["title"].isin(inputMovies_df["title"].tolist())]
inputMovies_df = pd.merge(inputId, inputMovies_df)
inputMovies_df.head()

   movieId                title  year  rating
0        1            Toy Story  1995     3.5
1        2              Jumanji  1995     2.0
2      296         Pulp Fiction  1994     5.0
3     1274                Akira  1988     4.5
4     1968  Breakfast Club, The  1985     5.0

In [11]:
inputMovies_df = inputMovies_df.drop("year", axis=1)
inputMovies_df.head()

   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0

In [12]:
commonUsers_df = rating_df[rating_df["movieId"].isin(inputMovies_df["movieId"].tolist())]
commonUsers_df.head()

     userId  movieId  rating
19        4      296     4.0
441      12     1968     3.0
479      13        2     2.0
531      13     1274     5.0
681      14      296     2.0

In [13]:
commonUsersGroup = commonUsers_df.groupby("userId")
commonUsersGroup.get_group(13)

     userId  movieId  rating
479      13        2     2.0
531      13     1274     5.0

In [17]:
commonUsersGroup = sorted(commonUsersGroup, key=lambda x: len(x[1]), reverse=True)
commonUsersGroup[:5]

[(75,
        userId  movieId  rating
  7507      75        1     5.0
  7508      75        2     3.5
  7540      75      296     5.0
  7633      75     1274     4.5
  7673      75     1968     5.0),
 (106,
        userId  movieId  rating
  9083     106        1     2.5
  9084     106        2     3.0
  9115     106      296     3.5
  9198     106     1274     3.0
  9238     106     1968     3.5),
 (686,
         userId  movieId  rating
  61336     686        1     4.0
  61337     686        2     3.0
  61377     686      296     4.0
  61478     686     1274     4.0
  61569     686     1968     5.0),
 (815,
         userId  movieId  rating
  73747     815        1     4.5
  73748     815        2     3.0
  73922     815      296     5.0
  74362     815     1274     3.0
  74678     815     1968     4.5),
 (1040,
         userId  movieId  rating
  96689    1040        1     3.0
  96690    1040        2     1.5
  96733    1040      296     3.5
  96859    1040     1274     3.0
  96922    1040     1968     4.0)]

In [19]:
top100Users = commonUsersGroup[:100]
top100Users[0:5]

[(75,
        userId  movieId  rating
  7507      75        1     5.0
  7508      75        2     3.5
  7540      75      296     5.0
  7633      75     1274     4.5
  7673      75     1968     5.0),
 (106,
        userId  movieId  rating
  9083     106        1     2.5
  9084     106        2     3.0
  9115     106      296     3.5
  9198     106     1274     3.0
  9238     106     1968     3.5),
 (686,
         userId  movieId  rating
  61336     686        1     4.0
  61337     686        2     3.0
  61377     686      296     4.0
  61478     686     1274     4.0
  61569     686     1968     5.0),
 (815,
         userId  movieId  rating
  73747     815        1     4.5
  73748     815        2     3.0
  73922     815      296     5.0
  74362     815     1274     3.0
  74678     815     1968     4.5),
 (1040,
         userId  movieId  rating
  96689    1040        1     3.0
  96690    1040        2     1.5
  96733    1040      296     3.5
  96859    1040     1274     3.0
  96922    1040     1968     4.0)]

In [20]:
personCorelationDict = {}

for name, group in top100Users:
    group = group.sort_values(by="movieId")
    inputMovies_df = inputMovies_df.sort_values(by="movieId")
    nRatings = len(group)
    similar_movies = inputMovies_df[inputMovies_df["movieId"].isin(group["movieId"].tolist())]
    similar_movies_ratings = similar_movies["rating"].tolist()
    all_ratings = group["rating"].tolist()
    Sxx = sum([i**2 for i in similar_movies_ratings]) - pow(sum(similar_movies_ratings), 2)/float(nRatings)
    Syy = sum([i**2 for i in all_ratings]) - pow(sum(all_ratings), 2)/float(nRatings)
    Sxy = sum( i*j for i, j in zip(similar_movies_ratings, all_ratings)) - sum(similar_movies_ratings)*sum(all_ratings)/float(nRatings)

    if Sxx != 0 and Syy != 0:
        personCorelationDict[name] = Sxy/np.sqrt(Sxx*Syy) 
    else:
        personCorelationDict[name] = 0

In [21]:
personCorelationDict

{75: np.float64(0.8272781516947562),
 106: np.float64(0.5860090386731182),
 686: np.float64(0.8320502943378437),
 815: np.float64(0.5765566601970551),
 1040: np.float64(0.9434563530497265),
 1130: np.float64(0.2891574659831201),
 1502: np.float64(0.8770580193070299),
 1599: np.float64(0.4385290096535153),
 1625: np.float64(0.716114874039432),
 1950: np.float64(0.179028718509858),
 2065: np.float64(0.4385290096535153),
 2128: np.float64(0.5860090386731196),
 2432: np.float64(0.1386750490563073),
 2791: np.float64(0.8770580193070299),
 2839: np.float64(0.8204126541423674),
 2948: np.float64(-0.11720180773462392),
 3025: np.float64(0.45124262819713973),
 3040: np.float64(0.89514359254929),
 3186: np.float64(0.6784622064861935),
 3271: np.float64(0.26989594817970664),
 3429: np.float64(0.0),
 3734: np.float64(-0.15041420939904673),
 4099: np.float64(0.05860090386731196),
 4208: np.float64(0.29417420270727607),
 4282: np.float64(-0.4385290096535115),
 4292: np.float64(0.6564386345361464),
 4415: np.float64(-0.11183835382312353),
 4586: np.float64(-0.9024852563942795),
 4725: np.float64(-0.08006407690254357),
 4818: np.float64(0.4885967564883424),
 5104: np.float64(0.7674257668936507),
 5165: np.float64(-0.4385290096535153),
 5547: np.float64(0.17200522903844556),
 6082: np.float64(-0.04728779924109591),
 6207: np.float64(0.9615384615384616),
 6366: np.float64(0.6577935144802716),
 6482: np.float64(0.0),
 6530: np.float64(-0.3516054232038709),
 7235: np.float64(0.6981407669689391),
 7403: np.float64(0.11720180773462363),
 7641: np.float64(0.7161148740394331),
 7996: np.float64(0.626600514784504),
 8008: np.float64(-0.22562131409856986),
 8086: np.float64(0.6933752452815365),
 8245: np.float64(0.0),
 8572: np.float64(0.8600261451922278),
 8675: np.float64(0.5370861555295773),
 9101: np.float64(-0.08600261451922278),
 9358: np.float64(0.692178738358485),
 9663: np.float64(0.193972725041952),
 9994: np.float64(0.5030272728659587),
 10248: np.float64(-0.24806946917841693),
 10315: np.float64(0.537086155529574),
 10368: np.float64(0.4688072309384945),
 10607: np.float64(0.41602514716892186),
 10707: np.float64(0.9615384615384616),
 10863: np.float64(0.6020183016345595),
 11314: np.float64(0.8204126541423654),
 11399: np.float64(0.517260600111872),
 11769: np.float64(0.9376144618769914),
 11827: np.float64(0.4902903378454601),
 12069: np.float64(0.0),
 12120: np.float64(0.9292940047327363),
 12211: np.float64(0.8600261451922278),
 12325: np.float64(0.9616783115081544),
 12916: np.float64(0.5860090386731196),
 12921: np.float64(0.6611073566849309),
 13053: np.float64(0.9607689228305227),
 13142: np.float64(0.6016568375961863),
 13260: np.float64(0.7844645405527362),
 13366: np.float64(0.8951435925492911),
 13768: np.float64(0.8770580193070289),
 13888: np.float64(0.2508726030021272),
 13923: np.float64(0.3516054232038718),
 13934: np.float64(0.17200522903844556),
 14529: np.float64(0.7417901772340937),
 14551: np.float64(0.537086155529574),
 14588: np.float64(0.21926450482675766),
 14984: np.float64(0.716114874039432),
 15137: np.float64(0.5860090386731196),
 15157: np.float64(0.9035841064985974),
 15466: np.float64(0.7205766921228921),
 15670: np.float64(0.516015687115336),
 15834: np.float64(0.22562131409856986),
 16292: np.float64(0.6577935144802716),
 16456: np.float64(0.7161148740394331),
 16506: np.float64(0.5481612620668942),
 17246: np.float64(0.48038446141526137),
 17438: np.float64(0.7093169886164387),
 17501: np.float64(0.8168748513121271),
 17502: np.float64(0.8272781516947562),
 17666: np.float64(0.7689238340176859),
 17735: np.float64(0.7042381820123422),
 17742: np.float64(0.3922322702763681),
 17757: np.float64(0.64657575013984),
 17854: np.float64(0.537086155529574),
 17897: np.float64(0.8770580193070289),
 17944: np.float64(0.2713848825944774),
 18301: np.float64(0.29838119751643016),
 18509: np.float64(0.1322214713369862)}

In [27]:
pearsonDF = pd.DataFrame.from_dict(personCorelationDict, orient="index")
pearsonDF.columns = ["similarityIndex"]
pearsonDF["userId"] = pearsonDF.index
pearsonDF.index = range(len(pearsonDF))
pearsonDF.head()

   similarityIndex  userId
0         0.827278      75
1         0.586009     106
2         0.832050     686
3         0.576557     815
4         0.943456    1040

In [28]:
topUsers = pearsonDF.sort_values(by="similarityIndex", ascending=False)[:50]
topUsers.head()

    similarityIndex  userId
64         0.961678   12325
34         0.961538    6207
55         0.961538   10707
67         0.960769   13053
4          0.943456    1040

In [29]:
topUsersRating = topUsers.merge(rating_df, left_on="userId", right_on="userId", how="inner")
topUsersRating.head()

   similarityIndex  userId  movieId  rating
0         0.961678   12325        1     3.5
1         0.961678   12325        2     1.5
2         0.961678   12325        3     3.0
3         0.961678   12325        5     0.5
4         0.961678   12325        6     2.5

In [30]:
topUsersRating["weightedRating"] = topUsersRating["similarityIndex"]*topUsersRating["rating"]
topUsersRating.head()

   similarityIndex  userId  movieId  rating  weightedRating
0         0.961678   12325        1     3.5        3.365874
1         0.961678   12325        2     1.5        1.442517
2         0.961678   12325        3     3.0        2.885035
3         0.961678   12325        5     0.5        0.480839
4         0.961678   12325        6     2.5        2.404196

In [31]:
tempTopUsersRating = topUsersRating.groupby("movieId").sum()[["similarityIndex", "weightedRating"]]
tempTopUsersRating.columns = ["sum_similarityIndex", "sum_weightedRating"]
tempTopUsersRating.head()

         sum_similarityIndex  sum_weightedRating
movieId
1                  38.376281          140.800834
2                  38.376281           96.656745
3                  10.253981           27.254477
4                   0.929294            2.787882
5                  11.723262           27.151751

In [32]:
recommendation_df = pd.DataFrame()
recommendation_df["weighted average recommendation score"] = tempTopUsersRating["sum_weightedRating"]/tempTopUsersRating["sum_similarityIndex"]
recommendation_df["movieId"] = tempTopUsersRating.index
recommendation_df.head()

         weighted average recommendation score  movieId
movieId
1                                     3.668955        1
2                                     2.518658        2
3                                     2.657941        3
4                                     3.000000        4
5                                     2.316058        5

In [35]:
recommendation_df = recommendation_df.sort_values(by="weighted average recommendation score", ascending=False)
recommendation_df.head(10)

         weighted average recommendation score  movieId
movieId
5073                                       5.0     5073
2284                                       5.0     2284
3329                                       5.0     3329
28                                         5.0       28
945                                        5.0      945
2848                                       5.0     2848
987                                        5.0      987
1024                                       5.0     1024
55067                                      5.0    55067
32792                                      5.0    32792

In [37]:
movies_df.loc[movies_df["movieId"].isin(recommendation_df.head(10)["movieId"].tolist())]

       movieId                                              title  year
27          28                                         Persuasion  1995
928        945                                            Top Hat  1935
969        987                                              Bliss  1997
1005      1024                              Three Caballeros, The  1945
2200      2284                                       Bandit Queen  1994
2763      2848  Othello (Tragedy of Othello: The Moor of Venic...  1952
3243      3329                           Year My Voice Broke, The  1987
4978      5073            Son's Room, The (Stanza del figlio, La)  2001
9987     32792                     Red Desert (Deserto rosso, Il)  1964
12111    55067                                            Requiem  2006